version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-mentories-ppessanhadev
    ports:
      - 8000:8000
    command: sh /entrypoint.sh
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app/

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    container_name: api-mentories-ppessanhadev-database
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
